language: node_js
cache:
    yarn: true
script:
    - yarn test:ci
    - yarn build
branches:
    only:
        - 'master'
deploy:
    skip_cleanup: true
    provider: firebase
    token: $FIREBASE_TOKEN
