language: node_js
addons:
    apt:
        packages:
            - libgconf-2-4
cache:
    yarn: true
    directories:
        - ~/.cache
branches:
    only:
        - 'master'
install:
    - yarn install --frozen-lockfile
script:
    - yarn test --ci --runInBand
    - yarn build
    - yarn start-server-and-test 'gatsby serve' 9000 'percy exec -- cypress run --record --key e4b1a6d2-5857-4976-8539-4516a9d7a5d3'
