language: node_js
addons:
    apt:
        packages:
            - libgconf-2-4
    chrome: stable
cache:
    yarn: true
    directories:
        - ~/.cache
branches:
    only:
        - 'master'
install:
    - yarn install --frozen-lockfile
script:
    - yarn test --ci --runInBand
    - yarn build
    - yarn e2e:ci
