language: node_js
cache:
    yarn: true
script:
    - yarn lint
    - yarn test:unit
    - yarn build
    - yarn test:regression
deploy:
    skip_cleanup: true
    provider: firebase
    token: $FIREBASE_TOKEN
