language: node_js
cache:
    yarn: true
script:
    - yarn test:unit
    - yarn build
    - yarn test:regression
branches:
    only:
        - 'master'
deploy:
    skip_cleanup: true
    provider: firebase
    token: $FIREBASE_TOKEN
